//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBlog.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations about {0}, author of this blog.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility settings.
        /// </summary>
        public static string AccessibilityFullTitle {
            get {
                return ResourceManager.GetString("AccessibilityFullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string AccessibilitySettingsFontTitle {
            get {
                return ResourceManager.GetString("AccessibilitySettingsFontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default font.
        /// </summary>
        public static string AccessibilitySettingsFontUseDefault {
            get {
                return ResourceManager.GetString("AccessibilitySettingsFontUseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the dyslexic font.
        /// </summary>
        public static string AccessibilitySettingsFontUseDylexia {
            get {
                return ResourceManager.GetString("AccessibilitySettingsFontUseDylexia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between two lines.
        /// </summary>
        public static string AccessibilitySettingsLineHeight {
            get {
                return ResourceManager.GetString("AccessibilitySettingsLineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default space.
        /// </summary>
        public static string AccessibilitySettingsLineHeight100 {
            get {
                return ResourceManager.GetString("AccessibilitySettingsLineHeight100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double space.
        /// </summary>
        public static string AccessibilitySettingsLineHeight200 {
            get {
                return ResourceManager.GetString("AccessibilitySettingsLineHeight200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple space.
        /// </summary>
        public static string AccessibilitySettingsLineHeight300 {
            get {
                return ResourceManager.GetString("AccessibilitySettingsLineHeight300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify the text.
        /// </summary>
        public static string AccessibilitySettingsSetTextIsJutified {
            get {
                return ResourceManager.GetString("AccessibilitySettingsSetTextIsJutified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align text on left.
        /// </summary>
        public static string AccessibilitySettingsSetTextIsNotJutified {
            get {
                return ResourceManager.GetString("AccessibilitySettingsSetTextIsNotJutified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alignment.
        /// </summary>
        public static string AccessibilitySettingsTextAlign {
            get {
                return ResourceManager.GetString("AccessibilitySettingsTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string AccessibilitySettingsZoom {
            get {
                return ResourceManager.GetString("AccessibilitySettingsZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string AccessibilityTheme {
            get {
                return ResourceManager.GetString("AccessibilityTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the dark theme.
        /// </summary>
        public static string AccessibilityThemeDark {
            get {
                return ResourceManager.GetString("AccessibilityThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default theme.
        /// </summary>
        public static string AccessibilityThemeDefault {
            get {
                return ResourceManager.GetString("AccessibilityThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the high contrast theme.
        /// </summary>
        public static string AccessibilityThemeHighContrast {
            get {
                return ResourceManager.GetString("AccessibilityThemeHighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives for {0}.
        /// </summary>
        public static string ArchivesDescription {
            get {
                return ResourceManager.GetString("ArchivesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all archives.
        /// </summary>
        public static string ArchivesListDescription {
            get {
                return ResourceManager.GetString("ArchivesListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the list of all archives.
        /// </summary>
        public static string ArchivesShowAll {
            get {
                return ResourceManager.GetString("ArchivesShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all categories.
        /// </summary>
        public static string CategoriesListDescription {
            get {
                return ResourceManager.GetString("CategoriesListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the list of all categories.
        /// </summary>
        public static string CategoriesShowAll {
            get {
                return ResourceManager.GetString("CategoriesShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts in the category &apos;{0}&apos;.
        /// </summary>
        public static string CategoryDescription {
            get {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact {0}, author of this blog.
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses cookies to allow us to enhance your browsing experience (accessibility settings). None personal data are collected or shared..
        /// </summary>
        public static string CookiesConcentContent {
            get {
                return ResourceManager.GetString("CookiesConcentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string CookiesConcentTitle {
            get {
                return ResourceManager.GetString("CookiesConcentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This website use cookie to enhance your browsing experience.&lt;/p&gt;
        ///Cookies that could be used are:
        ///&lt;ul&gt;&lt;li&gt;To save your settings.
        ///&lt;/li&gt;&lt;li&gt;To preserver your session when you are authenticated via social networks.
        ///&lt;/li&gt;&lt;li&gt;To analyze pages the most view, to have an idea about the content loved by users.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string CookiesPolityContent {
            get {
                return ResourceManager.GetString("CookiesPolityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations about our Cookie Policy.
        /// </summary>
        public static string CookiesPolityDescription {
            get {
                return ResourceManager.GetString("CookiesPolityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Policy.
        /// </summary>
        public static string CookiesPolityTitle {
            get {
                return ResourceManager.GetString("CookiesPolityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a personal weblog. The opinions expressed here represent my own and not those of my employer..
        /// </summary>
        public static string Disclamer {
            get {
                return ResourceManager.GetString("Disclamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we are not able to save your profile. Please try again later..
        /// </summary>
        public static string EditAccountError {
            get {
                return ResourceManager.GetString("EditAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is only used when you request to be notified of comments on post you are following..
        /// </summary>
        public static string EditAccountInformation {
            get {
                return ResourceManager.GetString("EditAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations saved..
        /// </summary>
        public static string EditAccountSuccess {
            get {
                return ResourceManager.GetString("EditAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {0},&lt;/p&gt;
        ///&lt;p&gt;A new comment has been hadded to the post &lt;a href=&apos;{1}&apos; alt=&apos;{2}&apos;&gt;&apos;{2}&apos;&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string EMailCommentAddedContent {
            get {
                return ResourceManager.GetString("EMailCommentAddedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment on &apos;{0}&apos;.
        /// </summary>
        public static string EMailCommentAddedSubject {
            get {
                return ResourceManager.GetString("EMailCommentAddedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {0},&lt;/p&gt;
        ///&lt;p&gt;Your mail was used on {1}. To ensure you have requested it, your e-mail will not be used without your validation.&lt;/p&gt;
        ///&lt;p&gt;If you want to be able to comment en receive comment updates, please use &lt;a href=&apos;{2}&apos; alt=&quot;Validation url&quot;&gt;this link&lt;/a&gt; to validate your e-mail.&lt;/p&gt;
        ///&lt;p&gt;If you cannot use this link, copy and past this url in your web browser : {2}&lt;/p&gt;
        ///&lt;p&gt;Best regards,&lt;/p&gt;.
        /// </summary>
        public static string EmailValidationContentFormat {
            get {
                return ResourceManager.GetString("EmailValidationContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail has not been validated yet. Please, check your mailbox..
        /// </summary>
        public static string EmailValidationStatusKo {
            get {
                return ResourceManager.GetString("EmailValidationStatusKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail has been validated..
        /// </summary>
        public static string EmailValidationStatusOk {
            get {
                return ResourceManager.GetString("EmailValidationStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail confirmation.
        /// </summary>
        public static string EmailValidationSubject {
            get {
                return ResourceManager.GetString("EmailValidationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results for this search..
        /// </summary>
        public static string EmptySearchResultMessage {
            get {
                return ResourceManager.GetString("EmptySearchResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a comment to add to this post.
        /// </summary>
        public static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message.
        /// </summary>
        public static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a display name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a subject for this message.
        /// </summary>
        public static string EnterSubject {
            get {
                return ResourceManager.GetString("EnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;An error occurred during the login process. We are sorry.&lt;/p&gt;&lt;p&gt;Please try again later.&lt;/p&gt;.
        /// </summary>
        public static string ExternalLoginCallbackError {
            get {
                return ResourceManager.GetString("ExternalLoginCallbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atom.
        /// </summary>
        public static string FeedAtom {
            get {
                return ResourceManager.GetString("FeedAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        public static string FeedRss {
            get {
                return ResourceManager.GetString("FeedRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeds.
        /// </summary>
        public static string Feeds {
            get {
                return ResourceManager.GetString("Feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more posts.
        /// </summary>
        public static string GetMorePost {
            get {
                return ResourceManager.GetString("GetMorePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more results.
        /// </summary>
        public static string GetMoreResults {
            get {
                return ResourceManager.GetString("GetMoreResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted on Microsoft Azure.
        /// </summary>
        public static string HostedOnAzure {
            get {
                return ResourceManager.GetString("HostedOnAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in.
        /// </summary>
        public static string LogInOrSignUp {
            get {
                return ResourceManager.GetString("LogInOrSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be logged in to comment this post..
        /// </summary>
        public static string LogInPriorToComment {
            get {
                return ResourceManager.GetString("LogInPriorToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using {0}.
        /// </summary>
        public static string LogInWith {
            get {
                return ResourceManager.GetString("LogInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logget out..
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Mail sended.&lt;/p&gt;&lt;p&gt;Thank you. I will reply as soon as possible.&lt;/p&gt;.
        /// </summary>
        public static string MailSended {
            get {
                return ResourceManager.GetString("MailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, We are not abble to send your mail..
        /// </summary>
        public static string MailSendError {
            get {
                return ResourceManager.GetString("MailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string NComments {
            get {
                return ResourceManager.GetString("NComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments.
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories of this article.
        /// </summary>
        public static string PostInfoCategories {
            get {
                return ResourceManager.GetString("PostInfoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of publication.
        /// </summary>
        public static string PostInfoDate {
            get {
                return ResourceManager.GetString("PostInfoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy .
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To  allow you to log in, this application have to store Open Auth informations shared by your providers (Facebook, Twitter.. .etc...). It si only technical data (token). Out of this application, this informations cannot be used and have none interest.&lt;/p&gt;&lt;p&gt;Informations collected when you are editing you profile are used only by this application and are not shared with third parties or other applications. At any time, you are able to edit/delete your informations. It will be permanently removed from the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyPolicyContent {
            get {
                return ResourceManager.GetString("PrivacyPolicyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations about our Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyDescription {
            get {
                return ResourceManager.GetString("PrivacyPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about this article.
        /// </summary>
        public static string ReadMoreAboutSuffix {
            get {
                return ResourceManager.GetString("ReadMoreAboutSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result for &apos;{0}&apos;.
        /// </summary>
        public static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string SenderMail {
            get {
                return ResourceManager.GetString("SenderMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a new validation mail.
        /// </summary>
        public static string SendValidationMail {
            get {
                return ResourceManager.GetString("SendValidationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we are not able to send a validation mail. Please check your porfile and try again later..
        /// </summary>
        public static string SendValidationMailError {
            get {
                return ResourceManager.GetString("SendValidationMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail send. Please check your mailbox..
        /// </summary>
        public static string SendValidationMailSuccess {
            get {
                return ResourceManager.GetString("SendValidationMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with.
        /// </summary>
        public static string ShareWith {
            get {
                return ResourceManager.GetString("ShareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more share options.
        /// </summary>
        public static string ShowMoreShareOptions {
            get {
                return ResourceManager.GetString("ShowMoreShareOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want receive an e-mail when someone post a comment to this post..
        /// </summary>
        public static string SubscribToCommentNotification {
            get {
                return ResourceManager.GetString("SubscribToCommentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we are not able to update yoursubscription Please try again later..
        /// </summary>
        public static string SubscribToCommentNotificationError {
            get {
                return ResourceManager.GetString("SubscribToCommentNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription has been updated..
        /// </summary>
        public static string SubscribToCommentNotificationSuccess {
            get {
                return ResourceManager.GetString("SubscribToCommentNotificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service have no rules. Be  fun, fine and benevolent to enjoy it..
        /// </summary>
        public static string TermsOfServiceContent {
            get {
                return ResourceManager.GetString("TermsOfServiceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Jérémy Jeanson.
        /// </summary>
        public static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
